name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Use Node.js
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Lint
      - name: Run ESLint
        run: npm run lint

      # 5. Build
      - name: Build Next.js app
        run: npm run build

      # 6. (Optional) Run tests
      - name: Run tests
        run: npm test
