name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint (non-blocking)
        run: npm run lint || echo "Lint warnings ignored"

      - name: Build Next.js app
        run: npm run build

      # Uncomment if tests exist
      # - name: Run tests
      #   run: npm test
